### ISSUE TITLE
Explanation Request

### ISSUE THREAD

**Issue by NikoCiminelliTufts** [kyegomez/RT-X#11]
Has this repo been deployed or tested at all? when I have taken this or the other RT rep down the model seems to be very small. That doesn't seem to make much sense based on the paper. Can you clarify this?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-X/issues/11">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-X/issues/11/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-X/issues/11/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@NikoCiminelliTufts Hello, can you be more specific? We're missing the efficient net and some things, we're still not done with the implementation.
