### ISSUE TITLE
Module not found error for zeta and classifier_free_guidance_pytorch 

### ISSUE THREAD

**Issue by DeeNihl** [kyegomez/RT-X#12]
Module not found error for zeta and classifier_free_guidance_pytorch 

**To Reproduce**
git clone this repo

pip install -r requirements.text

python rtx2_exzample.py

**Expected behavior**
a tensor like : (tensor([[[-0.1899, -0.2870,  0.4471,  ...,  0.8224,  0.1974,  0.5205],
         [-0.0617,  0.2402,  0.7786,  ...,  0.3528,  0.4517,  0.2858],
         [-0.1535, -0.4502,  0.4945,  ..., -0.0856,  0.5338,  0.1241],
         ...,

**Screenshots**

**Additional context**
Add the zeta and classifier_free_guidance_pytorch  to requirements.txt
I

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-X/issues/12">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-X/issues/12/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-X/issues/12/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@DeeNihl thanks I made a mistake with the requirements

**Comment by kyegomez** [comment]
@DeeNihl try again pls

**Comment by DeeNihl** [comment]
still missing classifier_free_guidance_pytorch but let me wipe and reclone to be sure

**Comment by DeeNihl** [comment]
Tested, issue resolved
