### ISSUE TITLE
Weights from the open source RTX-1 model 

### ISSUE THREAD

**Issue by SamuelSchmidgall** [kyegomez/RT-X#7]
Does this load the weights from the open source RTX-1 model that Google provided?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/kyegomez) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/kyegomez/RT-X/issues/7">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/kyegomez/RT-X/issues/7/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/kyegomez/RT-X/issues/7/pledge.svg">
</picture>
</a>

**Comment by kyegomez** [comment]
@SamuelSchmidgall No but you can try making a script for this?
